version: "3"

services:
  app:
    build: .
    image: ${IMAGE_NAME}:${IMAGE_TAG}

  ipmiserver:
    image: vaporio/ipmi-simulator

  test:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    command: make test
    depends_on:
      - ipmiserver
    volumes:
      - ".:/code"
